generation:
  max_new_tokens: 128
  do_sample: true
  temperature: 0.7
  top_p: 0.9
  num_beams: 3
  min_length: 20
  early_stopping: true
  repetition_penalty: 1.2
  length_penalty: 1.0
  no_repeat_ngram_size: 3

models:
  t5:
    encoder: "all-MiniLM-L6-v2"
    generator: "google/flan-t5-large"
  gpt:
    encoder: "all-mpnet-base-v2"
    generator: "tiiuae/falcon-7b-instruct"